CREATE TABLE [dbo].[TestTable]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Value	VARCHAR(100) NOT NULL,
	CreateDate	DATETIME NOT NULL DEFAULT GETDATE(),
	UpdateDate	DATETIME NOT NULL DEFAULT GETDATE()
)
